---
title: Automate product feedback reports using generative AI
file_name: Product Innovation using Generative AI and DataRobot Auto ML.ipynb
description: |-
  This notebook builds an automated system to process review text and use Generative AI to produce targeted reports for product design and manufacturing teams.
languages:
  - python
maintainers:
  - Jo√£o Gomes
maintainers_email:
  - joao.gomes@datarobot.com
tags: []
