---
title: Feature importance rank ensembling (FIRE)
file_name: feature_reduction_with_fire.ipynb
description: |-
  You can extend model ensembling, which provides improved accuracy and robustness, to feature selection.
  Within DataRobot, this approach is based on aggregating ranks of features using Feature Impact from several blueprints from the Leaderboard.
languages:
  - python
maintainers:
  - Jo√£o Gomes
maintainers_email:
  - joao.gomes@datarobot.com
tags: []
