---
title: Integrate Amazon SageMaker with DataRobot MLOps
file_name: AWS_SageMaker_DataRobot_MLOps.ipynb
description: |-
  This notebook walks you through the steps to train and host a SageMaker model that can be monitored in the DataRobot platform.
languages:
  - python
maintainers:
  - Oleksandr Saienko
  - Mao Shun (AWS)
maintainers_email:
  - oleksandr.saienko@datarobot.com
tags: []
