---
title: Multi-Model Analysis
file_name: Multi-Model Analysis.ipynb
description: |-
  This notebook shares three Python functions which can pull out various accuracy metrics, feature impact, and feature effects from multiple models and plot them in one chart.
languages:
  - python
maintainers:
  - Jake Snyder
maintainers_email:
  - jake.snyder@datarobot.com
tags: []
