---
title: DataRobot AutoML end-to-end with Amazon Athena
file_name: Amazon_S3_End_to_End.ipynb
description: |-
  This example notebook outlines how to read in an Amazon Athena table and upload it to DataRobot's AI Catalog.
  Then, using this dataset, we'll create a project, deploy the top performing model to a DataRobot prediction server, and make batch predictions with a test dataset.
languages:
  - python
maintainers:
  - Biju Krishnan
  - Jo√£o Gomes
maintainers_email:
  - biju.krishnan@datarobot.com
  - joao.gomes@datarobot.com
tags: []
