---
title: Introduction to DataRobotX
file_name: drx-overview.ipynb
description: |-
  This accelerator leverages the power of DataRobotx to quickly run the AutoML workflow on the Lending Club Dataset.
languages:
  - python
maintainers:
  - Jo√£o Gomes
maintainers_email:
  - joao@datarobot.com
tags: []
