title: Anti-Money Laundering (AML) Alert Scoring
file_name: Anti-Money Laundering (AML) Alert Scoring.ipynb
description: |-
  This use case aims to develop a machine learning model that utilizes historical data, including customer and transactional information, to identify alerts that resulted in the generation of a Suspicious Activity Report (SAR).
  The model will assign a suspicious activity score to future alerts, improving the effectiveness and efficiency of an AML compliance program by prioritizing alerts based on their ranking order according to the score.
languages:
  - python
maintainers:
  - Jo√£o Gomes
authors_email:
  - joao.gomes@datarobot.com
tags: []
