title: Create custom blueprints
file_name: create_custom_blueprint.ipynb
description: |-
  You may wish to customize DataRobot's blueprints by inserting your own custom code.
  Leverage Composable ML to build a new blueprint from scratch or swap out certain components for your own code.
languages:
  - python
authors: 
  - Joao Gomes
authors_email:
  - joao.gomes@datarobot.com
tags: []