title: Fine-tune models with Eureqa
file_name: fine_tuning_with_eureqa.ipynb
description: |-
  Eureqa is a symbolic regression algorithm that searches the space of mathematical expressions to find the best fit for a given dataset, while minimizing both error and complexity.
  Eureqa came out of Cornell's AI Lab in 2009, developed into a company called Nutonian, and then was acquired by DataRobot in 2017.
  Eureqa now lives as a blueprint within DataRobot.
languages:
  - python
maintainers:
  - Jo√£o Gomes
maintainers_email:
  - joao@datarobot.com
tags: []
