title: Netlift modeling
file_name: uplift_modeling.ipynb
description: |-
  This notebook covers a popular marketing use case often referred to as "netlift" or "uplift" modeling.
  This modeling approach is used when you want to isolate the impact of a marketing campaign (i.e., the "treatment" or the "intervention") on specific prospective clients.
languages:
  - python
authors: 
  - Matthias Kullowatz
authors_email:
  - matthias.kullowatz@datarobot.com
tags: []