title: Predict lumber prices with Ready Signal and time series forecasts
file_name: DataRobot_RXA.ipynb
description: |-
  This notebook guides you through the process of using Ready Signal to add external control data, such as census and weather data, to improve time series predictions.
languages:
  - python
maintainers:
  - Jack Claucherty
  - Jenna King
  - Baylen Springer
  - Matt Schaefer
  - Chen Wang
authors_email:
  - jack.claucherty@rxa.io
  - jenna.king@rxa.io
  - baylen.springer@readysignal.com
  - matt.schaefer@readysignal.com
  - chen.wang@datarobot.com
tags: []
