---
title: Create a deployment
file_name: Create_Deployments.ipynb
description: |-
  Take in the controller file from the first notebook, deploy the top models in each project, and add a "deployment" column to the controller.
languages:
  - python
maintainers:
  - Jo√£o Gomes
maintainers_email:
  - joao.gomes@datarobot.com
tags: []
