---
title: Get Leaderboard predictions
file_name: RequestPredictions_Deployment.ipynb
description: |-
  Obtain predictions from the models that have been deployed for a more robust and "production ready" approach than using the Leaderboard.
languages:
  - python
maintainers:
  - Jo√£o Gomes
maintainers_email:
  - joao.gomes@datarobot.com
tags: []
