---
title: Get Leaderboard predictions
file_name: RequestPredictions-leaderboard.ipynb
description: |-
  Obtain predictions from models created in the previous step to generate the "next day curve".
languages:
  - python
maintainers:
  - Jo√£o Gomes
maintainers_email:
  - joao.gomes@datarobot.com
tags: []
